### ISSUE TITLE
After a game over, the initial life and bomb settings are set to the amount of lives and bombs you died with

### ISSUE THREAD

**Issue by PatchMixolydic** [tboddy/tpj3#1]
Startup:
<img src="https://user-images.githubusercontent.com/8634700/122257885-0f2dad00-ce96-11eb-9356-7839254962fb.png" width=600 alt="The initial settings are three bombs and two lives.">

After a game over:
<img src="https://user-images.githubusercontent.com/8634700/122258047-3c7a5b00-ce96-11eb-89ad-1beb4876baa9.png" width=600 alt="The initial settings are two bombs and no lives.">

I was also able to reproduce this on BlastEm.
<img src="https://user-images.githubusercontent.com/8634700/122258540-c1657480-ce96-11eb-8576-a7f62e8a777f.png" width=600 alt="The game running in BlastEm. The initial settings are one bomb and no lives.">

**Comment by tboddy** [comment]
confirmed tysm

**Comment by tboddy** [comment]
fixed in 4c23799366318ea58726cb329dcc05d1fdeb7535

function 'resetGame' missing a few variable resets in addition to lives and bombs -- game over timer, current boss index
